# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: peterpeerdemanblog
google_analytics: UA-47494831-1
title: hashbang

production_url : http://hashbang.nl

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: hashbang

title : hashbang
tagline: Peter's epiphanies in tech for the world to behold.
author :
  name : Peter Peerdeman
  email : peter@peterpeerdeman.nl
  bio : learn love share drive create
  email_md5 : dd4c76470f1fd83c6dd7f4ec7873427a
  github : peterpeerdeman
  twitter : peterpeerdeman
  linkedin : peterpeerdeman
  feedburner : ~

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
  - jekyll-redirect-from
